insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("TV", "Electronic", 300, "LG", 30,"NEW")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Bag", "Fashion", 200, "GUCCI", 100,"2020 New")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Shoes", "Fashion", 10, "Adidas", 1000,"for sports")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("MacBookPro", "Electronic", 300,"Apple", 60,"16inches")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Bicycle", "Sports", 100, "SamchunRi", 200,"for riders")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Wallet", "Fashion", 90, "Channel", 20,"2019")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Mouse", "Electronic", 1, "Samsung", 300,"wireless")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Sofa", "Furniture", 1000, "IKEA", 300,"cow leather")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("T-shirts", "Fashion", 5,"Noke", 400,"black, white")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("BawlingBall", "Sports", 20, "Storm", 24,"12pound")
